# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogHelper\Import.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Import(object):
    def setupUi(self, Import):
        Import.setObjectName("Import")
        Import.resize(499, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Import.sizePolicy().hasHeightForWidth())
        Import.setSizePolicy(sizePolicy)
        Import.setWindowOpacity(1.0)
        Import.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(Import)
        self.layoutWidget.setGeometry(QtCore.QRect(-1, -1, 501, 565))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_select_files = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b_select_files.setFont(font)
        self.b_select_files.setStyleSheet("background-color: rgb(222, 248, 248);\n"
"")
        self.b_select_files.setIconSize(QtCore.QSize(16, 20))
        self.b_select_files.setAutoDefault(False)
        self.b_select_files.setDefault(False)
        self.b_select_files.setFlat(False)
        self.b_select_files.setObjectName("b_select_files")
        self.horizontalLayout.addWidget(self.b_select_files)
        spacerItem = QtWidgets.QSpacerItem(187, 39, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.b_import_data = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b_import_data.setFont(font)
        self.b_import_data.setAutoFillBackground(False)
        self.b_import_data.setStyleSheet("background-color: rgb(222, 248, 248);\n"
"")
        self.b_import_data.setIconSize(QtCore.QSize(16, 20))
        self.b_import_data.setFlat(False)
        self.b_import_data.setObjectName("b_import_data")
        self.horizontalLayout.addWidget(self.b_import_data)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.results_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.results_table.setMinimumSize(QtCore.QSize(481, 479))
        self.results_table.setStyleSheet("")
        self.results_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.results_table.setIconSize(QtCore.QSize(5, 5))
        self.results_table.setColumnCount(3)
        self.results_table.setObjectName("results_table")
        self.results_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(58, 232, 232, 32))
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.results_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.results_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.results_label = QtWidgets.QLabel(self.layoutWidget)
        self.results_label.setMinimumSize(QtCore.QSize(0, 21))
        self.results_label.setText("")
        self.results_label.setObjectName("results_label")
        self.horizontalLayout_2.addWidget(self.results_label)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Import)
        QtCore.QMetaObject.connectSlotsByName(Import)

    def retranslateUi(self, Import):
        _translate = QtCore.QCoreApplication.translate
        Import.setWindowTitle(_translate("Import", "Import"))
        self.b_select_files.setText(_translate("Import", "Import Files"))
        self.b_import_data.setText(_translate("Import", "Save to Database"))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("Import", "Date"))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("Import", "Time"))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("Import", "Comment"))
