# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogHelper\LogHelper_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("favicon.ico")
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.b_date_previous = QtWidgets.QToolButton(self.centralwidget)
        self.b_date_previous.setMaximumSize(QtCore.QSize(20, 20))
        self.b_date_previous.setAutoFillBackground(False)
        self.b_date_previous.setIconSize(QtCore.QSize(12, 12))
        self.b_date_previous.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_date_previous.setAutoRaise(True)
        self.b_date_previous.setArrowType(QtCore.Qt.LeftArrow)
        self.b_date_previous.setObjectName("b_date_previous")
        self.horizontalLayout_2.addWidget(self.b_date_previous)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 20))
        self.dateEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.dateEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.b_date_next = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_date_next.sizePolicy().hasHeightForWidth())
        self.b_date_next.setSizePolicy(sizePolicy)
        self.b_date_next.setMaximumSize(QtCore.QSize(20, 20))
        self.b_date_next.setIconSize(QtCore.QSize(12, 12))
        self.b_date_next.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_date_next.setAutoRaise(True)
        self.b_date_next.setArrowType(QtCore.Qt.RightArrow)
        self.b_date_next.setObjectName("b_date_next")
        self.horizontalLayout_2.addWidget(self.b_date_next)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.l_show_date = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.l_show_date.setFont(font)
        self.l_show_date.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.l_show_date.setObjectName("l_show_date")
        self.verticalLayout.addWidget(self.l_show_date)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScrollMargin(10)
        self.tableWidget.setIconSize(QtCore.QSize(5, 5))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(58, 232, 232, 32))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.formWidget = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formWidget.setObjectName("formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dpr_prev24 = QtWidgets.QTextEdit(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpr_prev24.sizePolicy().hasHeightForWidth())
        self.dpr_prev24.setSizePolicy(sizePolicy)
        self.dpr_prev24.setMinimumSize(QtCore.QSize(0, 50))
        self.dpr_prev24.setMaximumSize(QtCore.QSize(16777215, 9999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpr_prev24.setFont(font)
        self.dpr_prev24.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.dpr_prev24.setObjectName("dpr_prev24")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dpr_prev24)
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(113, 50))
        self.label_2.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dpr_next24 = QtWidgets.QTextEdit(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpr_next24.sizePolicy().hasHeightForWidth())
        self.dpr_next24.setSizePolicy(sizePolicy)
        self.dpr_next24.setMinimumSize(QtCore.QSize(0, 50))
        self.dpr_next24.setMaximumSize(QtCore.QSize(16777215, 9999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpr_next24.setFont(font)
        self.dpr_next24.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.dpr_next24.setObjectName("dpr_next24")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dpr_next24)
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(113, 20))
        self.label_3.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dpr_location = QtWidgets.QLineEdit(self.formWidget)
        self.dpr_location.setMinimumSize(QtCore.QSize(0, 20))
        self.dpr_location.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpr_location.setFont(font)
        self.dpr_location.setObjectName("dpr_location")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dpr_location)
        self.label_4 = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(113, 20))
        self.label_4.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dpr_task_reports = QtWidgets.QLineEdit(self.formWidget)
        self.dpr_task_reports.setMinimumSize(QtCore.QSize(20, 20))
        self.dpr_task_reports.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpr_task_reports.setFont(font)
        self.dpr_task_reports.setObjectName("dpr_task_reports")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dpr_task_reports)
        self.label_5 = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(113, 20))
        self.label_5.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dpr_comments = QtWidgets.QLineEdit(self.formWidget)
        self.dpr_comments.setMinimumSize(QtCore.QSize(20, 20))
        self.dpr_comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpr_comments.setFont(font)
        self.dpr_comments.setObjectName("dpr_comments")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dpr_comments)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.b_clear_dpr = QtWidgets.QPushButton(self.formWidget)
        self.b_clear_dpr.setObjectName("b_clear_dpr")
        self.horizontalLayout_6.addWidget(self.b_clear_dpr)
        self.b_save_dpr = QtWidgets.QPushButton(self.formWidget)
        self.b_save_dpr.setObjectName("b_save_dpr")
        self.horizontalLayout_6.addWidget(self.b_save_dpr)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label = QtWidgets.QLabel(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(113, 50))
        self.label.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout_3.addWidget(self.formWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setMinimumSize(QtCore.QSize(80, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_save = QtWidgets.QPushButton(self.groupBox)
        self.b_save.setMinimumSize(QtCore.QSize(0, 20))
        self.b_save.setObjectName("b_save")
        self.verticalLayout_7.addWidget(self.b_save)
        self.dpr_pdf_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.dpr_pdf_checkbox.setObjectName("dpr_pdf_checkbox")
        self.verticalLayout_7.addWidget(self.dpr_pdf_checkbox)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.formWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setContentsMargins(3, 0, 3, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(118, 40))
        self.label_6.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.shf_prev12_a = QtWidgets.QPlainTextEdit(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shf_prev12_a.sizePolicy().hasHeightForWidth())
        self.shf_prev12_a.setSizePolicy(sizePolicy)
        self.shf_prev12_a.setMinimumSize(QtCore.QSize(0, 50))
        self.shf_prev12_a.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_prev12_a.setFont(font)
        self.shf_prev12_a.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.shf_prev12_a.setObjectName("shf_prev12_a")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shf_prev12_a)
        self.label_7 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(122, 40))
        self.label_7.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.shf_next12_a = QtWidgets.QPlainTextEdit(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shf_next12_a.sizePolicy().hasHeightForWidth())
        self.shf_next12_a.setSizePolicy(sizePolicy)
        self.shf_next12_a.setMinimumSize(QtCore.QSize(0, 50))
        self.shf_next12_a.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_next12_a.setFont(font)
        self.shf_next12_a.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.shf_next12_a.setObjectName("shf_next12_a")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shf_next12_a)
        self.label_8 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(122, 20))
        self.label_8.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.shf_location_a = QtWidgets.QLineEdit(self.formWidget_2)
        self.shf_location_a.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_location_a.setMaximumSize(QtCore.QSize(999999, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_location_a.setFont(font)
        self.shf_location_a.setObjectName("shf_location_a")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.shf_location_a)
        self.label_9 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(122, 23))
        self.label_9.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.shf_equipment_a = QtWidgets.QLineEdit(self.formWidget_2)
        self.shf_equipment_a.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_equipment_a.setMaximumSize(QtCore.QSize(999999, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_equipment_a.setFont(font)
        self.shf_equipment_a.setObjectName("shf_equipment_a")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shf_equipment_a)
        self.label_10 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(124, 22))
        self.label_10.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.shf_safety_a = QtWidgets.QLineEdit(self.formWidget_2)
        self.shf_safety_a.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_safety_a.setMaximumSize(QtCore.QSize(999999, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_safety_a.setFont(font)
        self.shf_safety_a.setObjectName("shf_safety_a")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.shf_safety_a)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.b_clear_shf_a = QtWidgets.QPushButton(self.formWidget_2)
        self.b_clear_shf_a.setObjectName("b_clear_shf_a")
        self.horizontalLayout_7.addWidget(self.b_clear_shf_a)
        self.b_save_shf_a = QtWidgets.QPushButton(self.formWidget_2)
        self.b_save_shf_a.setObjectName("b_save_shf_a")
        self.horizontalLayout_7.addWidget(self.b_save_shf_a)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_13 = QtWidgets.QLabel(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(122, 19))
        self.label_13.setMaximumSize(QtCore.QSize(999999, 9999999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.shf_comments_a = QtWidgets.QLineEdit(self.formWidget_2)
        self.shf_comments_a.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_comments_a.setMaximumSize(QtCore.QSize(999999, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_comments_a.setFont(font)
        self.shf_comments_a.setObjectName("shf_comments_a")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.shf_comments_a)
        self.verticalLayout_5.addWidget(self.formWidget_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_4.setMaximumSize(QtCore.QSize(160, 72))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_4.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAcceptDrops(False)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.l_shf_name_a = QtWidgets.QLabel(self.groupBox_4)
        self.l_shf_name_a.setGeometry(QtCore.QRect(0, 20, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_shf_name_a.setFont(font)
        self.l_shf_name_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_shf_name_a.setObjectName("l_shf_name_a")
        self.l_shf_shift_a = QtWidgets.QLabel(self.groupBox_4)
        self.l_shf_shift_a.setGeometry(QtCore.QRect(0, 40, 161, 20))
        self.l_shf_shift_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_shf_shift_a.setObjectName("l_shf_shift_a")
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setMaximumSize(QtCore.QSize(160, 72))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAcceptDrops(False)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.b_shf_create_a = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_shf_create_a.setFont(font)
        self.b_shf_create_a.setObjectName("b_shf_create_a")
        self.verticalLayout_8.addWidget(self.b_shf_create_a)
        self.b_shf_pdf_a = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_shf_pdf_a.setFont(font)
        self.b_shf_pdf_a.setObjectName("b_shf_pdf_a")
        self.verticalLayout_8.addWidget(self.b_shf_pdf_a)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.formWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setContentsMargins(3, 0, 3, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(118, 40))
        self.label_14.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.shf_prev12_b = QtWidgets.QPlainTextEdit(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shf_prev12_b.sizePolicy().hasHeightForWidth())
        self.shf_prev12_b.setSizePolicy(sizePolicy)
        self.shf_prev12_b.setMinimumSize(QtCore.QSize(0, 50))
        self.shf_prev12_b.setMaximumSize(QtCore.QSize(16777215, 9999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_prev12_b.setFont(font)
        self.shf_prev12_b.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.shf_prev12_b.setObjectName("shf_prev12_b")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shf_prev12_b)
        self.label_15 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(122, 40))
        self.label_15.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.shf_next12_b = QtWidgets.QPlainTextEdit(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shf_next12_b.sizePolicy().hasHeightForWidth())
        self.shf_next12_b.setSizePolicy(sizePolicy)
        self.shf_next12_b.setMinimumSize(QtCore.QSize(0, 50))
        self.shf_next12_b.setMaximumSize(QtCore.QSize(16777215, 9999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_next12_b.setFont(font)
        self.shf_next12_b.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.shf_next12_b.setObjectName("shf_next12_b")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shf_next12_b)
        self.label_16 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(122, 20))
        self.label_16.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.shf_location_b = QtWidgets.QLineEdit(self.formWidget_3)
        self.shf_location_b.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_location_b.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_location_b.setFont(font)
        self.shf_location_b.setObjectName("shf_location_b")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.shf_location_b)
        self.label_17 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(122, 23))
        self.label_17.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.shf_equipment_b = QtWidgets.QLineEdit(self.formWidget_3)
        self.shf_equipment_b.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_equipment_b.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_equipment_b.setFont(font)
        self.shf_equipment_b.setObjectName("shf_equipment_b")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shf_equipment_b)
        self.label_18 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(124, 22))
        self.label_18.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.shf_safety_b = QtWidgets.QLineEdit(self.formWidget_3)
        self.shf_safety_b.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_safety_b.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_safety_b.setFont(font)
        self.shf_safety_b.setObjectName("shf_safety_b")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.shf_safety_b)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.b_clear_shf_b = QtWidgets.QPushButton(self.formWidget_3)
        self.b_clear_shf_b.setObjectName("b_clear_shf_b")
        self.horizontalLayout_8.addWidget(self.b_clear_shf_b)
        self.b_save_shf_b = QtWidgets.QPushButton(self.formWidget_3)
        self.b_save_shf_b.setObjectName("b_save_shf_b")
        self.horizontalLayout_8.addWidget(self.b_save_shf_b)
        self.formLayout_3.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_19 = QtWidgets.QLabel(self.formWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(122, 18))
        self.label_19.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.shf_comments_b = QtWidgets.QLineEdit(self.formWidget_3)
        self.shf_comments_b.setMinimumSize(QtCore.QSize(202, 20))
        self.shf_comments_b.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shf_comments_b.setFont(font)
        self.shf_comments_b.setObjectName("shf_comments_b")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.shf_comments_b)
        self.verticalLayout_6.addWidget(self.formWidget_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_5.setMaximumSize(QtCore.QSize(160, 72))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_5.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAcceptDrops(False)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 70, 83, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.l_shf_name_b = QtWidgets.QLabel(self.groupBox_5)
        self.l_shf_name_b.setGeometry(QtCore.QRect(0, 20, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_shf_name_b.setFont(font)
        self.l_shf_name_b.setAlignment(QtCore.Qt.AlignCenter)
        self.l_shf_name_b.setObjectName("l_shf_name_b")
        self.l_shf_shift_b = QtWidgets.QLabel(self.groupBox_5)
        self.l_shf_shift_b.setGeometry(QtCore.QRect(0, 40, 161, 20))
        self.l_shf_shift_b.setAlignment(QtCore.Qt.AlignCenter)
        self.l_shf_shift_b.setObjectName("l_shf_shift_b")
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setMaximumSize(QtCore.QSize(160, 72))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_6.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAcceptDrops(False)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.b_shf_create_b = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_shf_create_b.setFont(font)
        self.b_shf_create_b.setObjectName("b_shf_create_b")
        self.verticalLayout_9.addWidget(self.b_shf_create_b)
        self.b_shf_pdf_b = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.b_shf_pdf_b.setFont(font)
        self.b_shf_pdf_b.setObjectName("b_shf_pdf_b")
        self.verticalLayout_9.addWidget(self.b_shf_pdf_b)
        self.horizontalLayout_10.addWidget(self.groupBox_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 21))
        self.menubar.setObjectName("menubar")
        self.menucool = QtWidgets.QMenu(self.menubar)
        self.menucool.setObjectName("menucool")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.statusbar.setFont(font)
        self.statusbar.setToolTipDuration(5)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCopy_Day = QtWidgets.QAction(MainWindow)
        self.actionCopy_Day.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionCopy_Day.setIconVisibleInMenu(False)
        self.actionCopy_Day.setShortcutVisibleInContextMenu(True)
        self.actionCopy_Day.setObjectName("actionCopy_Day")
        self.actionPaste_Day = QtWidgets.QAction(MainWindow)
        self.actionPaste_Day.setEnabled(False)
        self.actionPaste_Day.setIconVisibleInMenu(False)
        self.actionPaste_Day.setObjectName("actionPaste_Day")
        self.actionRandom_Background = QtWidgets.QAction(MainWindow)
        self.actionRandom_Background.setObjectName("actionRandom_Background")
        self.actionToday_s_Log = QtWidgets.QAction(MainWindow)
        self.actionToday_s_Log.setObjectName("actionToday_s_Log")
        self.actionDPR = QtWidgets.QAction(MainWindow)
        self.actionDPR.setObjectName("actionDPR")
        self.actionSHF_A = QtWidgets.QAction(MainWindow)
        self.actionSHF_A.setObjectName("actionSHF_A")
        self.actionSHF_B = QtWidgets.QAction(MainWindow)
        self.actionSHF_B.setObjectName("actionSHF_B")
        self.actionALL = QtWidgets.QAction(MainWindow)
        self.actionALL.setObjectName("actionALL")
        self.actionALL_2 = QtWidgets.QAction(MainWindow)
        self.actionALL_2.setObjectName("actionALL_2")
        self.actionClear_Log = QtWidgets.QAction(MainWindow)
        self.actionClear_Log.setObjectName("actionClear_Log")
        self.actionWindow_always_in_front = QtWidgets.QAction(MainWindow)
        self.actionWindow_always_in_front.setCheckable(True)
        self.actionWindow_always_in_front.setChecked(True)
        self.actionWindow_always_in_front.setObjectName("actionWindow_always_in_front")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionImport_Log_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Log_Data.setObjectName("actionImport_Log_Data")
        self.actionAuto_Sort_Log = QtWidgets.QAction(MainWindow)
        self.actionAuto_Sort_Log.setCheckable(True)
        self.actionAuto_Sort_Log.setChecked(True)
        self.actionAuto_Sort_Log.setObjectName("actionAuto_Sort_Log")
        self.menucool.addAction(self.actionOpen)
        self.menucool.addAction(self.actionSave)
        self.menucool.addAction(self.actionSettings)
        self.menucool.addAction(self.actionImport_Log_Data)
        self.menuEdit.addAction(self.actionCopy_Day)
        self.menuEdit.addAction(self.actionPaste_Day)
        self.menuEdit.addAction(self.actionAuto_Sort_Log)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear_Log)
        self.menuView.addAction(self.actionRandom_Background)
        self.menuView.addAction(self.actionWindow_always_in_front)
        self.menuView.addAction(self.actionSearch)
        self.menubar.addAction(self.menucool.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log Helper"))
        self.b_date_previous.setText(_translate("MainWindow", "..."))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.b_date_next.setText(_translate("MainWindow", "..."))
        self.l_show_date.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Comment"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_11.setText(_translate("MainWindow", "DAILY PROGRESS REPORT"))
        self.label_2.setText(_translate("MainWindow", "Pending Work\n"
"(Next 24 Hours)"))
        self.label_3.setText(_translate("MainWindow", "Location / Status"))
        self.label_4.setText(_translate("MainWindow", "Task Reports"))
        self.label_5.setText(_translate("MainWindow", "Comments"))
        self.b_clear_dpr.setText(_translate("MainWindow", "Clear"))
        self.b_save_dpr.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Work Completed\n"
"(Previous 24 Hours)"))
        self.groupBox.setTitle(_translate("MainWindow", "Reports"))
        self.b_save.setText(_translate("MainWindow", "Create Report"))
        self.dpr_pdf_checkbox.setText(_translate("MainWindow", "Create PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_12.setText(_translate("MainWindow", "SHIFT HANDOVER FORM"))
        self.label_6.setText(_translate("MainWindow", "Work Completed\n"
"(Previous 12 Hours)"))
        self.label_7.setText(_translate("MainWindow", "Pending Work\n"
"(Next 12 Hours)"))
        self.label_8.setText(_translate("MainWindow", "Location / Status"))
        self.label_9.setText(_translate("MainWindow", "Equipment Updates"))
        self.label_10.setText(_translate("MainWindow", "Safety Considerations"))
        self.b_clear_shf_a.setText(_translate("MainWindow", "Clear"))
        self.b_save_shf_a.setText(_translate("MainWindow", "Save"))
        self.label_13.setText(_translate("MainWindow", "Comments"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Shift Info"))
        self.l_shf_name_a.setText(_translate("MainWindow", "l_shf_name_a"))
        self.l_shf_shift_a.setText(_translate("MainWindow", "l_shf_shift_a"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reports"))
        self.b_shf_create_a.setText(_translate("MainWindow", "Create Report"))
        self.b_shf_pdf_a.setText(_translate("MainWindow", "Create PDF"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "SHIFT A"))
        self.label_30.setText(_translate("MainWindow", "SHIFT HANDOVER FORM"))
        self.label_14.setText(_translate("MainWindow", "Work Completed\n"
"(Previous 12 Hours)"))
        self.label_15.setText(_translate("MainWindow", "Pending Work\n"
"(Next 12 Hours)"))
        self.label_16.setText(_translate("MainWindow", "Location / Status"))
        self.label_17.setText(_translate("MainWindow", "Equipment Updates"))
        self.label_18.setText(_translate("MainWindow", "Safety Considerations"))
        self.b_clear_shf_b.setText(_translate("MainWindow", "Clear"))
        self.b_save_shf_b.setText(_translate("MainWindow", "Save"))
        self.label_19.setText(_translate("MainWindow", "Comments"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Shift Info"))
        self.checkBox_9.setText(_translate("MainWindow", "Create Email"))
        self.l_shf_name_b.setText(_translate("MainWindow", "l_shf_name_b"))
        self.l_shf_shift_b.setText(_translate("MainWindow", "l_shf_shift_b"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Reports"))
        self.b_shf_create_b.setText(_translate("MainWindow", "Create Report"))
        self.b_shf_pdf_b.setText(_translate("MainWindow", "Create PDF"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "SHIFT B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "SHF"))
        self.menucool.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save All"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionCopy_Day.setText(_translate("MainWindow", "Copy Day"))
        self.actionCopy_Day.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionPaste_Day.setText(_translate("MainWindow", "Paste Day"))
        self.actionPaste_Day.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.actionRandom_Background.setText(_translate("MainWindow", "Random Background"))
        self.actionToday_s_Log.setText(_translate("MainWindow", "Log"))
        self.actionDPR.setText(_translate("MainWindow", "DPR"))
        self.actionSHF_A.setText(_translate("MainWindow", "SHF A"))
        self.actionSHF_B.setText(_translate("MainWindow", "SHF B"))
        self.actionALL.setText(_translate("MainWindow", "ALL"))
        self.actionALL_2.setText(_translate("MainWindow", "ALL"))
        self.actionClear_Log.setText(_translate("MainWindow", "Clear Log"))
        self.actionWindow_always_in_front.setText(_translate("MainWindow", "Window always in front"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionImport_Log_Data.setText(_translate("MainWindow", "Import Log Data"))
        self.actionAuto_Sort_Log.setText(_translate("MainWindow", "Auto Sort Log"))
