# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Surveyor\Documents\pythonProjects\LogHelper\Settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(549, 333)
        self.b_settings_save = QtWidgets.QPushButton(Dialog)
        self.b_settings_save.setGeometry(QtCore.QRect(389, 302, 66, 23))
        self.b_settings_save.setObjectName("b_settings_save")
        self.b_settings_cancel = QtWidgets.QPushButton(Dialog)
        self.b_settings_cancel.setGeometry(QtCore.QRect(469, 302, 66, 23))
        self.b_settings_cancel.setObjectName("b_settings_cancel")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(-7, 0, 541, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-10, 20, 551, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.l_option1_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_7.setFont(font)
        self.l_option1_7.setObjectName("l_option1_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_option1_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.s_dpr_template = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_dpr_template.setObjectName("s_dpr_template")
        self.horizontalLayout_4.addWidget(self.s_dpr_template)
        self.b_dpr_template = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_dpr_template.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_dpr_template.setAutoRaise(True)
        self.b_dpr_template.setArrowType(QtCore.Qt.NoArrow)
        self.b_dpr_template.setObjectName("b_dpr_template")
        self.horizontalLayout_4.addWidget(self.b_dpr_template)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.l_option1_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_2.setFont(font)
        self.l_option1_2.setObjectName("l_option1_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_option1_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.s_dpr_output_doc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_dpr_output_doc.setObjectName("s_dpr_output_doc")
        self.horizontalLayout_6.addWidget(self.s_dpr_output_doc)
        self.b_dpr_output_doc = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_dpr_output_doc.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_dpr_output_doc.setAutoRaise(True)
        self.b_dpr_output_doc.setArrowType(QtCore.Qt.NoArrow)
        self.b_dpr_output_doc.setObjectName("b_dpr_output_doc")
        self.horizontalLayout_6.addWidget(self.b_dpr_output_doc)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.l_option1_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_4.setFont(font)
        self.l_option1_4.setObjectName("l_option1_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l_option1_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.s_dpr_output_pdf = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_dpr_output_pdf.setObjectName("s_dpr_output_pdf")
        self.horizontalLayout_7.addWidget(self.s_dpr_output_pdf)
        self.b_dpr_output_pdf = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_dpr_output_pdf.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_dpr_output_pdf.setAutoRaise(True)
        self.b_dpr_output_pdf.setArrowType(QtCore.Qt.NoArrow)
        self.b_dpr_output_pdf.setObjectName("b_dpr_output_pdf")
        self.horizontalLayout_7.addWidget(self.b_dpr_output_pdf)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.l_option1_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_5.setFont(font)
        self.l_option1_5.setObjectName("l_option1_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_option1_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.s_shf_template = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_shf_template.setObjectName("s_shf_template")
        self.horizontalLayout_8.addWidget(self.s_shf_template)
        self.b_shf_template = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_shf_template.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_shf_template.setAutoRaise(True)
        self.b_shf_template.setArrowType(QtCore.Qt.NoArrow)
        self.b_shf_template.setObjectName("b_shf_template")
        self.horizontalLayout_8.addWidget(self.b_shf_template)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.l_option1_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_6.setFont(font)
        self.l_option1_6.setObjectName("l_option1_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.l_option1_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.s_shf_output_doc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_shf_output_doc.setObjectName("s_shf_output_doc")
        self.horizontalLayout_9.addWidget(self.s_shf_output_doc)
        self.b_shf_output_doc = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_shf_output_doc.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_shf_output_doc.setAutoRaise(True)
        self.b_shf_output_doc.setArrowType(QtCore.Qt.NoArrow)
        self.b_shf_output_doc.setObjectName("b_shf_output_doc")
        self.horizontalLayout_9.addWidget(self.b_shf_output_doc)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.l_option1_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_option1_14.setFont(font)
        self.l_option1_14.setObjectName("l_option1_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.l_option1_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.s_shf_output_pdf = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.s_shf_output_pdf.setObjectName("s_shf_output_pdf")
        self.horizontalLayout_10.addWidget(self.s_shf_output_pdf)
        self.b_shf_output_pdf = QtWidgets.QToolButton(self.formLayoutWidget)
        self.b_shf_output_pdf.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.b_shf_output_pdf.setAutoRaise(True)
        self.b_shf_output_pdf.setArrowType(QtCore.Qt.NoArrow)
        self.b_shf_output_pdf.setObjectName("b_shf_output_pdf")
        self.horizontalLayout_10.addWidget(self.b_shf_output_pdf)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 541, 132))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.s_name1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_name1.setObjectName("s_name1")
        self.gridLayout.addWidget(self.s_name1, 1, 1, 1, 1)
        self.s_title1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_title1.setObjectName("s_title1")
        self.gridLayout.addWidget(self.s_title1, 1, 2, 1, 1)
        self.s_shift1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_shift1.setObjectName("s_shift1")
        self.gridLayout.addWidget(self.s_shift1, 1, 3, 1, 1)
        self.s_name2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_name2.setObjectName("s_name2")
        self.gridLayout.addWidget(self.s_name2, 2, 1, 1, 1)
        self.s_title2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_title2.setObjectName("s_title2")
        self.gridLayout.addWidget(self.s_title2, 2, 2, 1, 1)
        self.s_shift2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_shift2.setObjectName("s_shift2")
        self.gridLayout.addWidget(self.s_shift2, 2, 3, 1, 1)
        self.s_name3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_name3.setObjectName("s_name3")
        self.gridLayout.addWidget(self.s_name3, 3, 1, 1, 1)
        self.s_title3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_title3.setObjectName("s_title3")
        self.gridLayout.addWidget(self.s_title3, 3, 2, 1, 1)
        self.s_shift3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_shift3.setObjectName("s_shift3")
        self.gridLayout.addWidget(self.s_shift3, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 541, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(False)
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 541, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formGroupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.formGroupBox_2.setGeometry(QtCore.QRect(-2, 19, 551, 131))
        self.formGroupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formGroupBox_2)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox.setMinimumSize(QtCore.QSize(118, 0))
        self.checkBox.setObjectName("checkBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_6 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_6)
        self.line = QtWidgets.QFrame(self.formGroupBox_2)
        self.line.setMinimumSize(QtCore.QSize(225, 0))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.line)
        self.line_5 = QtWidgets.QFrame(self.formGroupBox_2)
        self.line_5.setMinimumSize(QtCore.QSize(100, 0))
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox_2.setMinimumSize(QtCore.QSize(118, 0))
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_5)
        self.line_2 = QtWidgets.QFrame(self.formGroupBox_2)
        self.line_2.setMinimumSize(QtCore.QSize(225, 0))
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.line_6 = QtWidgets.QFrame(self.formGroupBox_2)
        self.line_6.setMinimumSize(QtCore.QSize(100, 0))
        self.line_6.setLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_6)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox_3.setMinimumSize(QtCore.QSize(118, 0))
        self.checkBox_3.setAccessibleName("4")
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_4)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(8, 301, 372, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusbar = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.statusbar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statusbar.setText("")
        self.statusbar.setObjectName("statusbar")
        self.horizontalLayout.addWidget(self.statusbar)
        self.a_open_browse = QtWidgets.QAction(Dialog)
        self.a_open_browse.setObjectName("a_open_browse")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.b_settings_save.setText(_translate("Dialog", "Save"))
        self.b_settings_cancel.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "FILE LOCATIONS"))
        self.l_option1_7.setText(_translate("Dialog", "DPR Template File"))
        self.b_dpr_template.setText(_translate("Dialog", "..."))
        self.l_option1_2.setText(_translate("Dialog", "DPR Output Folder (DOC)"))
        self.b_dpr_output_doc.setText(_translate("Dialog", "..."))
        self.l_option1_4.setText(_translate("Dialog", "DPR Output Folder (PDF)"))
        self.b_dpr_output_pdf.setText(_translate("Dialog", "..."))
        self.l_option1_5.setText(_translate("Dialog", "SHF Template File"))
        self.b_shf_template.setText(_translate("Dialog", "..."))
        self.l_option1_6.setText(_translate("Dialog", "SHF Output Folder (DOC)"))
        self.b_shf_output_doc.setText(_translate("Dialog", "..."))
        self.l_option1_14.setText(_translate("Dialog", "SHF Output Folder (PDF)"))
        self.b_shf_output_pdf.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Files"))
        self.label_7.setText(_translate("Dialog", "Person 2"))
        self.label_6.setText(_translate("Dialog", "Person 1"))
        self.label_4.setText(_translate("Dialog", "Job Title"))
        self.label_3.setText(_translate("Dialog", "Name"))
        self.label_5.setText(_translate("Dialog", "Shift"))
        self.label_8.setText(_translate("Dialog", "Person 3"))
        self.label_9.setText(_translate("Dialog", "USERS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Users"))
        self.label_2.setText(_translate("Dialog", "OPTIONS"))
        self.checkBox.setText(_translate("Dialog", "Comment Colors"))
        self.checkBox_6.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_2.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_5.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_3.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Main"))
        self.a_open_browse.setText(_translate("Dialog", "Browse"))
        self.a_open_browse.setToolTip(_translate("Dialog", "Browse"))
